name: Wine Runner Qemu Extra Builder (arm)
run-name: ${{ github.action }} Building Wine Runner Qemu Extra (arm)

on:
  push:
  workflow_dispatch:

jobs:  
  Debian10:
    runs-on: ubuntu-latest
    steps:
        - name: Clone Repository
          uses: actions/checkout@v3

        - name: Configure System
          run: |
            bash .github/workflows/configure-building-enviroment-without-x86.sh arm64 buster

        - name: Building Python3
          run: |
            bash .github/workflows/run-command-in-chroot.sh .github/workflows/configure-python3.sh

        - name: Get Resources
          run: |
            CPU_CORES=$(($(grep -c processor < /proc/cpuinfo)*2))
            bash .github/workflows/run-command-in-chroot.sh make download-loong64-ed2k -j$CPU_CORES
            bash .github/workflows/run-command-in-chroot.sh make download-virtio-iso -j$CPU_CORES

        - name: Building Qemu Packager
          id: buildingQemuPackager
          run: |
            
            # 构建 deb 包
            bash .github/workflows/run-command-in-chroot.sh dpkg-buildpackage -b
            # 删除 dbg 包
            bash .github/workflows/run-command-in-chroot.sh rm -v ../*dbg*.deb -rfv
            # 获取 deb 位置
            cp system-bottle/*.deb . -rv | true
            echo "fileName=$(ls -1 *.deb)" >> $GITHUB_OUTPUT

        - name: Upload Result
          uses: actions/upload-artifact@v1
          with:
            name: spark-deepin-wine-runner-qemu-system-extra~buster
            path: ${{ steps.buildingQemuPackager.outputs.fileName }}

  Debian11:
    runs-on: ubuntu-latest
    steps:
        - name: Clone Repository
          uses: actions/checkout@v3

        - name: Configure System
          run: |
            bash .github/workflows/configure-building-enviroment-without-x86.sh arm64 bullseye

        - name: Get Resources
          run: |
            CPU_CORES=$(($(grep -c processor < /proc/cpuinfo)*2))
            bash .github/workflows/run-command-in-chroot.sh make download-loong64-ed2k -j$CPU_CORES
            bash .github/workflows/run-command-in-chroot.sh make download-virtio-iso -j$CPU_CORES

        - name: Building Qemu Packager
          id: buildingQemuPackager
          run: |
            
            # 构建 deb 包
            bash .github/workflows/run-command-in-chroot.sh dpkg-buildpackage -b
            # 删除 dbg 包
            bash .github/workflows/run-command-in-chroot.sh rm -v ../*dbg*.deb -rfv
            # 获取 deb 位置
            cp system-bottle/*.deb . -rv | true
            echo "fileName=$(ls -1 *.deb)" >> $GITHUB_OUTPUT

        - name: Upload Result
          uses: actions/upload-artifact@v1
          with:
            name: spark-deepin-wine-runner-qemu-system-extra~buster
            path: ${{ steps.buildingQemuPackager.outputs.fileName }}

  Debian12:
    runs-on: ubuntu-latest
    steps:
        - name: Clone Repository
          uses: actions/checkout@v3

        - name: Configure System
          run: |
            bash .github/workflows/configure-building-enviroment-without-x86.sh arm64 bookworm

        - name: Get Resources
          run: |
            CPU_CORES=$(($(grep -c processor < /proc/cpuinfo)*2))
            bash .github/workflows/run-command-in-chroot.sh make download-loong64-ed2k -j$CPU_CORES
            bash .github/workflows/run-command-in-chroot.sh make download-virtio-iso -j$CPU_CORES

        - name: Building Qemu Packager
          id: buildingQemuPackager
          run: |
            
            # 构建 deb 包
            bash .github/workflows/run-command-in-chroot.sh dpkg-buildpackage -b
            # 删除 dbg 包
            bash .github/workflows/run-command-in-chroot.sh rm -v ../*dbg*.deb -rfv
            # 获取 deb 位置
            cp system-bottle/*.deb . -rv | true
            echo "fileName=$(ls -1 *.deb)" >> $GITHUB_OUTPUT

        - name: Upload Result
          uses: actions/upload-artifact@v1
          with:
            name: spark-deepin-wine-runner-qemu-system-extra~buster
            path: ${{ steps.buildingQemuPackager.outputs.fileName }}

